config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  resources :diaries
  resources :emotion_logs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# == Schema Information
#
# Table name: diaries
#
#  id         :integer          not null, primary key
#  content    :text
#  image      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string
#  adress     :string
#
class Diary < ApplicationRecord
end

app/models/emotion_log.rb
# == Schema Information
#
# Table name: emotion_logs
#
#  id          :integer          not null, primary key
#  recorded_at :datetime         not null
#  image_url   :string           not null
#  happiness   :float            not null
#  neutral     :float            not null
#  sadness     :float            not null
#  surprise    :float            not null
#  anger       :float            not null
#  contempt    :float            not null
#  disgust     :float            not null
#  fear        :float            not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class EmotionLog < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


   belongs_to :user
   has_attached_file :file, default_url: "missing.jpg"

   def face_detection
  Curl.post("https://api.projectoxford.ai/face/v1.0/detect", "{ url: '#{self.file.url}' }" ) do |curl|
   curl.headers["Ocp-Apim-Subscription-Key"] = Rails.application.secrets.microsoft['face_api_key']
   curl.headers["Content-Type"] = 'application/json'
     end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  #管理対象の「Diary」の一覧を表示する
  def index
    #新しい投稿６個を順に表示する（creatrd_atは作成された日時）
    @diaries = Diary.order(creatrd_at: :desc).limit(5)
  end

  # 管理対象の「Diary」を新規登録する画面を返すアクション（ルーティングに対応する処理の受け口になるメソッド）。
  def new
    @diary = Diary.new
  end

  # 管理対象の「Diary」を新しく作って永続化するアクション。
  def create
    @diary = Diary.new(diary_params)

    if @diary.save
      #保存できた場合show画面に遷移する
      redirect_to :action => "index"
    else
      #保存できなかった場合new画面に遷移する
      redirect_to :action => "new"
    end
  end

  #「Diary」内の検索したいidを取得して表示する
  def show
    @diary= Diary.find(params[:id])
  end

  # idに該当するdiaryを取得し編集画面を返す
  def edit
    @diary = Diary.find(params[:id])
  end

  # idに該当するdiaryを取得し更新する
  def update
    diary = Diary.find(params[:id])
    if diary.update(diary_params)
      #管理対象の「Diary」のidが更新できたら show画面に遷移する
      redirect_to :action =>"show", :id =>diary.id
    else
      #管理対象の「Diary」のidが更新できなかったら new画面に遷移する
      redirect_to :action =>"new"
    end
  end

  # 管理対象の「Diary」のidを取得し削除するアクション
  def destroy
    diary = diary.find(params[:id])
    diary.destroy
    redirect_to action: :index
  end

  #以下のメソッドはDiariesControllerクラス内のみで実行出来る
  private

  #diary_paramsメソッドを定義
  def diary_params

    #paramsから取得するデータのオブジェクト名diaryのtitle, contentのキーを指定する
    params.require(:diary).permit(:title, :content)
  end
end

app/controllers/emotion_logs_controller.rb
# 「EmotionLog」に関するリクエストを受け付けるコントローラのクラス定義
class EmotionLogsController < ApplicationController
  # 管理対象の「EmotionLog」を新規登録する画面を返すアクション（ルーティングに対応する処理の受け口になるメソッド）。
  def new
    # 新規登録画面で使用する「EnotionLog」のインスタンス（モデルクラスの実体）を生成する。
    @emotion_log = EmotionLog.new
  end

  # 管理対象の「EmotionLog」を詳細情報を見せる画面を返すアクション。
  def show
  end

  # 管理対象の「EmotionLog」を新しく作って永続化するアクション。
  def create
    @emotion_log = EmotionLog.new(emotion_log_params)

    #POST {Endpoint}/face/v1.0/detect?returnFaceId={returnFaceId}&returnFaceLandmarks={returnFaceLandmarks}&returnFaceAttributes={returnFaceAttributes}&recognitionModel={recognitionModel}&returnRecognitionModel={returnRecognitionModel}&detectionModel={detectionModel}&faceIdTimeToLive={faceIdTimeToLive}
    #アクセスしたいURLを書く
    uri = URI.parse("https://20010214.cognitiveservices.azure.com/face/v1.0/detect")
    #HTTPの設定
    http = Net::HTTP.new(uri.host, 443)
    #httpsを使うかどうか
    http.use_ssl = true
    #httpsを使う場合
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    #実際に送るリクエストボディーの設定
    message = "{\"url\":\"https://upload.wikimedia.org/wikipedia/commons/c/c3/RH_Louise_Lillian_Gish.jpg\"}"

    #microsoftのAPIに投げるための画像データを取得する
    response = http.start do
      #リクエストを投げる
      req = Net::HTTP::Post.new(uri.path)
      req.add_field('Ocp-Apim-Subscription-Key', '003383e0b0d2445f92a3b87d59a15a23')
      req.add_field('Content-Type', 'application/json')
      #リクエストボディの設定
      req.body = message
      #リクエストを送る 解析された結果がresponseに入る
      http.request(req)
    end
    @result = JSON.parse(response.body)
    Rails.logger.info(self) { "レスポンス: #{@result}" }

    # TODO: @result から各感情分析結果を取り出す
    # TODO: 取り出した感情分析結果でemotion_logに値を詰める

    # curl \
    #   -H "Ocp-Apim-Subscription-Key: 003383e0b0d2445f92a3b87d59a15a23" \
    #   "https://20010214.cognitiveservices.azure.com/face/v1.0/detect?detectionModel=detection_01&returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=emotion"\
    #   -H "Content-Type: application/json"\
    #   --data-ascii "{\"url\":\"https://upload.wikimedia.org/wikipedia/commons/c/c3/RH_Louise_Lillian_Gish.jpg\"}"

    #p→ログに出すメソッド inspect→オブジェクトの中身を加工
    #p @result.inspect
    #@id = @result[0]["id"]
    #@name = @result[0]["name"]
    #@email = @result[0]["email"]
    #@zipcode = @result[0]["zipcode"]
    #@county = @result[0]["county"]

    # 永続化対象の「EmotionLog」のインスタンスの記録日時に現在日時を代入する。
    @emotion_log.recorded_at = Time.zone.now
   #永続化対象の「EmotionLog」のインスタンスの幸福度に初期値として 0 を代入する。
   @emotion_log.anger = 0.03 #@result[0]['faceAttributes']['emotion']['anger']
   @emotion_log.happiness = 0.01 #@result[0]['faceAttributes']['emotion']['hapiness']
   @emotion_log.neutral = 0.0 #@result[0]['faceAttributes']['emotion']['neutral']
   @emotion_log.surprise = 0.0 #@result[0]['faceAttributes']['emotion']['surprise']
   @emotion_log.sadness = 0.05 #@result[0]['faceAttributes']['emotion']['sadness']
   @emotion_log.contempt = 0.08 #@result[0]['faceAttributes']['emotion']['contempt']
   @emotion_log.disgust = 0.02 #@result[0]['faceAttributes']['emotion']['disgust']
   @emotion_log.fear = 0.03 #@result[0]['faceAttributes']['emotion']['fear']


    #保存対象の「EmotionLog」を条件分岐する
    if @emotion_log.save
      #保存できた場合show画面に遷移する
      redirect_to emotion_log_path(@emotion_log)
    else
      #保存できなかった場合new画面に遷移する
      redirect_to :action => "new"
    end
  end

   def index
    @emotion_logs = EmotionLog.all
   end

  def show
    #「EmotionLog」内の検索したいidを取得して表示する
    @emotion_log = EmotionLog.find(params[:id])
  end

  def emotion_log_params

    params
      #emotion_logモデルのパラメータ群を受け取る
      .require(:emotion_log)
      #利用可能なパラメータ名image_urlを指定
      .permit(:image_url)
  end
end

#1 ストロングパラメータと１５行目の記述
#2 33行目のボディで設定 ←メッセージという変数の中身にURLの入ったJsonを入れる
#３ 21行目
#4  35行目
#5  39行目

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/index.html.erb
<%= stylesheet_link_tag 'diaries', media: 'all', 'data-turbolinks-track': 'reload' %>
<main>
  <div class="box">
    <%=link_to "新規投稿へ", new_diary_path %>

    <div class="diaries-container">
    <% @diaries.each do |d| %>
      <div class="diary">
        <%= d.content %>
        <%=d.created_at%>
        <%=link_to"詳細へ",diary_path(d.id)%>
        <%= link_to "編集する", edit_diary_path(d.id) %>
        <%= button_to "削除する", diary_path(d.id), method: :delete %>
        <%= button_to "削除する",diary_path(d.id),method: :delete%>
      </div>
    <%end%>
  </div>

</main>

app/views/diaries/new.html.erb
 <link rel="stylesheet" type="text/css" href="stylesheets/diaries.scss">



<div class ="katamari">
      <%= form_for @diary do |d| %>

    <div class="field">
        <%= d.label :title %>
        <%= d.text_field :title, :size => "30x2"  %>
    </div>

    <div class="field">
        <%= d.label :content %>
        <%= d.text_area :content, :size => "30x3"  %>
    </div>

        <%= d.submit "気持ち日記を投稿する" %>
        <% end %>

    <%= link_to "気持ち日記一覧に戻る", diaries_path %>
</div>

app/views/diaries/show.html.erb
<!DOCTYPE html><html>
<head>
     <link rel="stylesheet" type="text/css" href="stylesheets/diaries.scss">
    <title>Document</title></head>
    
    <body>

        <header>
            
            <a href="index.html" class="logo"><img src="./images/logo.png"></a>
           
            <div id="nav-button" class="nav-button">
            <a class="button1">気持ち日記</a>
            <a class="button2">気持ち診断</a>
            </div>
        </header>

        <main>
<div class = "content">
<h1>気持ち日記</h1>
<h3>気持ち日記詳細</h3>
<div class="diary">
  <p><%= @diary.content %></p>
  <p><%= @diary.created_at %></p>
</div>

<%= link_to "気持ち日記一覧に戻る", diarys_path %>



</div>

        </main>
        </html>

app/views/emotion_logs/index.html.erb
<% @emotion_logs.each do |t| %>
<%= t.happiness %>
<% end %>

app/views/emotion_logs/new.html.erb
<div class="content10">
  <div class="nakami2">
    <p class="setsumei1">AIで顔認識するとあなたの気持ちを察して言葉をかけてくれます。早速気持ち診断して声をかけてもらいしょう！</p>
    <h2>Add New URL</h2>

    <%= form_for :emotion_log, url: emotion_logs_path do |f| %>
      <p>
        <%= f.text_field :image_url, placeholder: 'URLを入力してください' %>
        <% if @emotion_log.errors.messages[:address].any? %>
          <span class="error">
            <%= @emotion_log.errors.messages[:address][0] %>
          </span>
        <% end %>
      </p>
      <p>
        <%= f.submit "登録する" %>
      </p>
    <% end %>
  </div>
</div>

app/views/emotion_logs/show.html.erb
<div class = "pic"></div>
<div class = "shindankekka">
<img src = "https://upload.wikimedia.org/wikipedia/commons/c/c3/RH_Louise_Lillian_Gish.jpg",width="400px"height="400px">
<div class = "box">
<div class>診断結果</div>
<p>happiness(幸福）:<%= @emotion_log.happiness %></p>
<p>neutral（平常）:<%= @emotion_log.neutral %></p>
<p>sadness（悲しみ）:<%= @emotion_log.sadness %></p>
<p>surprise(驚き）:<%= @emotion_log.surprise %></p>
<p>anger(怒り):<%= @emotion_log.anger %></p>
<p>contempt(軽蔑):<%= @emotion_log.contempt%></p>
<p>disgust(嫌悪):<%= @emotion_log.disgust %></p>
<p>fear(恐怖):<%= @emotion_log.fear%></p>
</div>
</div>
    </body>

</html>

app/views/emotion_logs/upload.html.erb
<h2>Add New URL</h2>

<%= form_for :website, url: websites_path do |f| %>
  <p>
    <%= f.text_field :address, placeholder: 'URLを入力してください' %>
    <% if @website.errors.messages[:address].any? %>
      <span class="error">
        <%= @website.errors.messages[:address][0] %>
      </span>
    <% end %>
  </p>
  <p>
    <%= f.submit "登録する" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neba2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <a href="index.html" class="logo"><img src="./images/logo.png"></a>

      <div id="nav-button" class="nav-button">
       <div class="button0">
        <%= link_to 'HOME', :controller => "top", :action => "index",class:""%>
        </div>
        <div class="button1">
        <%= link_to '気持ち日記', :controller => "diaries", :action => "new",class:"link"%>
        </div>
        <div class="button2">
        <%= link_to '気持ち診断', :controller => "emotion_logs", :action => "new" %>
        </div>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<!DOCTYPE html><html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif&display=swap" rel="stylesheet" /><link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /><link rel="stylesheet" href="top.css">
    <title>Document</title></head>

<body>


    <main>
        <div class ="nakami">
            <img src="../../../assets/v38_2.png" alt="ハートの写真" width="100%">
            <div class="neba-info">
                一般社団法人NeBA(ティーン向けメンタルヘルス自助団体)は学生を対象にメンタルヘルスに関する活動を行う団体です。<br>本サービスは学生のみならず誰でも気軽に自分のヘルスケアができる１.気持ち日記、２.気持ち診断の２つの機能を搭載したWebアプリケーションです。
            </div>

            <div class="kinou">
                <div class = "katamari1">
                    <div class = "nikki">気持ち日記</div>
                        <div class ="content1">
                            <p>自分の日々の気持ちを書き留めて<br>見返せるようにしてみましょう</p>
                        <div class ="bighako">
                            <div class ="hako">
                              <div class="button3">
                              <%= link_to '入り口', :controller => "diaries", :action => "new",class:"link"%>
                              </div>
                            </div>
                            <div class ="hako">
                              <img src="../../../assets/v9_15.png" alt="日記の写真"class="logo-image">
                            </div>
                        </div>
                        </div>
                    </div>

                    <div class = "katamari2">
                        <div class = "sindan">気持ち診断</div>
                            <div class ="content2">
                                <p>AIで自分の顔を認識すると今のあなた<br>の気持ちに言葉をかけてくれます。</p>
                          <div class ="bighako">
                            <div class ="hako">
                                <div class="button4">
                                <%= link_to '入り口', :controller => "emotion_logs", :action => "new",class:"link"%>
                                </div>
                            </div>
                            <div class ="hako">
                                <img src="../../../assets/v9_14.png" alt="診断の写真"class="logo-image">
                            </div>
                        </div>
                        </div>
                    </div>
                </div>


    </main>
    <fotter>
        <div class="fotter1">
            <p class="oomoji">一般社団法人NeBA</p>
            <p class="komoji">©2022 一般社団法人NeBA</p>
        </div>
    </fotter>

</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>